### ISSUE TITLE
Clarify the order of messages for "read up to" receipts

### ISSUE THREAD

**Issue by andybalaam** [matrix-org/matrix-spec#1503] opened 2023-04-27 09:17 UTC
**Link to problem area**: https://spec.matrix.org/v1.5/client-server-api/#receipts

**Issue**
 Under "Receipts" and probably in other places, we refer the order of messages. For example, the referenced section:

> To prevent this from becoming a problem, receipts are implemented using “up to” markers. This marker indicates that the acknowledgement applies to all events “up to and including” the event specified.

It is not clear what ordering is being used when talking about reading up to a point.

I am aware that there are ideas of [stream ordering](https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv3sync) and [topological ordering](https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv1roomsroomidrelationseventid) but I can't find a definition of these terms, and I don't see a reference to which ordering is used for receipts.

**Comment by richvdh** [comment] 2023-04-27 09:31
related: https://github.com/matrix-org/matrix-spec/issues/125

**Comment by richvdh** [comment] 2023-04-27 09:33
oh, and https://github.com/matrix-org/matrix-spec/issues/1334

**Comment by richvdh** [comment] 2023-04-27 09:34
actually this might be a duplicate of https://github.com/matrix-org/matrix-spec/issues/1167

**Comment by andybalaam** [comment] 2023-04-27 12:14
Yep, duplicate of #1167

**Comment by andybalaam** [comment] 2023-04-27 12:15
Duplicate of '#1167

**Closed** 2023-04-27 12:15 UTC
Labels: clarification
