### ISSUE TITLE
The 'Content' section of `m.receipt` is empty

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-spec#1343] opened 2022-11-15 19:44 UTC
**Link to problem area**: https://spec.matrix.org/v1.4/client-server-api/#mreceipt

**Issue**
The "Content" section of `m.receipt` should feature table(s) describing the fields and types that an `m.receipt` can be populated with. Instead, it is just a blank space.

**Expected behaviour**
A rendered set of tables representing [the m.receipt schema](https://github.com/matrix-org/matrix-spec/blob/main/data/event-schemas/schema/m.receipt.yaml) should be visible.

**Comment by anoadragon453** [comment] 2022-11-15 19:55
This might be due to the use of `patternProperties`?

https://github.com/matrix-org/matrix-spec/blob/bc15d4f9bcaccb87ed62effab14ee2bf1456c4e7/data/event-schemas/schema/m.receipt.yaml#L12

`m.ignored_user_list.yaml` uses the same:

https://github.com/matrix-org/matrix-spec/blob/bc15d4f9bcaccb87ed62effab14ee2bf1456c4e7/data/event-schemas/schema/m.ignored_user_list.yaml#L15

and no "Ignored User" table appears in the spec: https://spec.matrix.org/v1.4/client-server-api/#mignored_user_list

It also appears that `patternProperties` doesn't exist in OpenAPI 2.0, and was only added in https://github.com/OAI/OpenAPI-Specification/issues/687, so arguably we shouldn't even be using it until we support OpenAPI 3.1 (see https://github.com/matrix-org/matrix-spec/pull/1310 for upgrading to OpenAPI 3.1. Doing so does not magically fix this issue however).

**Comment by turt2live** [comment] 2022-11-15 19:59
I'm pretty sure this is a duplicate of the issue I can't find where we discovered that `additionalProperties` wasn't properly rendered. Whether the field is supported by OpenAPI or not is irrelevant - we define the templates for how these things get rendered.

**Comment by anoadragon453** [comment] 2022-11-15 20:04
@turt2live

> I'm pretty sure this is a duplicate of the issue I can't find where we discovered that `additionalProperties` wasn't properly rendered.

Do you mean `patternProperties`? Indeed, I see no mention of the text `patternProperties` outside of these two OpenAPI definition files, so we presumably have no handling of them in our rendering code.

**Comment by turt2live** [comment] 2022-11-15 20:08
I mean `additionalProperties` - I think we fixed it somewhat recently. `patternProperties`, for all intents and purposes, is effectively the same.

**Closed** 2023-09-27 12:42 UTC
Labels: spec-bug
