### ISSUE TITLE
Define "topological ordering" and link to it

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-spec#1253] opened 2022-09-26 22:41 UTC
We use the phrase "ordered topologically" and "topological ordering" throughout the spec, but never link to what that means. As far as I can tell, we also don't define what "topological" even is - we should define it and link to it everywhere.

**Comment by richvdh** [comment] 2022-11-14 15:35
closing as a duplicate of https://github.com/matrix-org/matrix-spec/issues/1334, which has more detail

**Closed by richvdh** 2022-11-14 15:35 UTC
Labels: clarification, client-server, s2s
