### ISSUE TITLE
Spec does not describe what the visibility conditions for a space or room in `/hierarchy` are

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/matrix-spec#1402] opened 2023-01-13 11:02 UTC
**Link to problem area**: https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv1roomsroomidhierarchy

**Issue**
From this description I can't find out what I need to do in order to ensure that a space I create will be visible to non-members in its parent space.
Or further, as a homeserver implementer I would have no idea what the conditions should be and I'd have to study Synapse source code I guess.

**Comment by reivilibre** [comment] 2023-01-13 11:21
In https://github.com/matrix-org/synapse/pull/14834 I dug up Synapse's definition:

> Calculate whether the room should be shown to the requester.
> 
> It should return true if:
> 
> * The requesting **local user** is joined or can join the room (per MSC3173) — *this typically means `join_rules` of `public` or `knock`*; or
> * The requesting **remote homeserver** has any user that is joined or can join the room; or
> * The history visibility is set to world readable.

It's not clear how `{guest_access: "can_join"}` interacts here but the issue I'm working on — https://github.com/matrix-org/conference-bot/issues/142 — suggests that it is needed in the space for things to work properly...

**Comment by clokep** [comment] 2023-01-13 12:21
Duplicate of #1184.

To my memory this is not related to `guest_access` at all, but I might be forgetting something!

**Comment by clokep** [comment] 2023-01-13 12:22
> this typically means join_rules of public or knock; or

Or that the user fulfills one of the restricted join rule checks.

**Comment by turt2live** [comment] 2023-01-13 16:21
Duplicate of https://github.com/matrix-org/matrix-spec/issues/1184

**Closed by turt2live** 2023-01-13 16:21 UTC
Labels: clarification
