### ISSUE TITLE
No clear way to delete your avatar/profile picture

### ISSUE THREAD

**Issue by gabrc52** [matrix-org/matrix-spec#1606] opened 2023-07-30 22:44 UTC
**Link to problem area**: https://spec.matrix.org/latest/client-server-api/#profiles

**Issue**

It does not state how to remove a user's avatar. By inspecting Element's network requests, I can see that you have to set it to the empty string. 

The docs for `PUT /_matrix/client/v3/profile/{userId}/avatar_url` do not state that `avatar_url` is a required parameter, so not specifying the key or setting it to null are plausible ways to remove it. If you do not specify the key, Synapse gives a `M_MISSING_PARAM`. If `null`, Synapse gives a `M_INVALID_PARAM`. Other homeserver implementations may do something different, since it is not specified what should happen.

Additionally, there is no `DELETE /_matrix/client/v3/profile/{userId}/avatar_url`. That would be the most intuitive to use, but would require modifying the spec and implementations rather than just a clarification.

**Comment by turt2live** [comment] 2023-07-31 06:13
Duplicate of https://github.com/matrix-org/matrix-spec/issues/378 (and friends)

**Closed by turt2live** 2023-07-31 06:13 UTC
Labels: clarification
