### ISSUE TITLE
Spec does not define what an event ID's grammar is, for room versions 1 and 2.

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/matrix-spec#1224] opened 2022-09-02 11:38 UTC
**Link to problem area**:
* https://spec.matrix.org/v1.3/rooms/v1/
* https://spec.matrix.org/v1.3/rooms/v2/

* (it's not on https://spec.matrix.org/v1.3/rooms/ either)

https://spec.matrix.org/v1.3/appendices/#room-ids-and-event-ids says:

> The format of an event ID depends upon the room version specification.

and links to the above pages. However none of those pages appear to tell you the grammar for v1.

**Issue**

It's unclear what the grammar for event IDs is; e.g. do they need to have a colon-separated domain name in?

The rule for redactions:

> If the domain of the event_id of the event being redacted is the same as the domain of the event_id of the [m.room](http://m.room/).redaction, allow.

suggests that they must do.

Further, Synapse won't accept a V1/V2 event without a domain and it enforces that the domain is one that has a signature on the event.

**Comment by richvdh** [comment] 2022-09-02 15:00
duplicate of #551

**Closed by richvdh** 2022-09-02 15:00 UTC
Labels: clarification
