### ISSUE TITLE
Remove message "just for me"

### ISSUE THREAD

**Issue by Wallby** [matrix-org/matrix-spec#871] opened 2021-07-31 12:55 UTC
**Suggestion**

Not sure if this already has been requested (searching for "remove message" did not spot it). I would like to be able to remove a message "just for me" (i.e. similar to how this can also be done in facebook messenger).

**Comment by zecakeh** [comment] 2022-03-02 23:08
Isn't this a duplicate of #19?

**Comment by anoadragon453** [comment] 2022-03-03 11:35
> Isn't this a duplicate of https://github.com/matrix-org/matrix-spec/issues/19?

It is, yes. That issue also calls for the ability to show those messages again if desired. I'm going to close this issue in favour of that one.

**Closed by anoadragon453** 2022-03-03 11:35 UTC
Labels: enhancement
