### ISSUE TITLE
It is not easy to navigate between different versions of the spec

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-spec#1130] opened 2022-06-15 14:12 UTC
I keep thinking that blue text here 

![image](https://user-images.githubusercontent.com/8614563/173848033-cb053ccd-35f5-457c-953b-1d717a3d8a02.png)

is a hyperlink or some kind of drop down menu that will let me navigate between older spec versions. It's not. I would love to see us [make it so](https://www.youtube.com/watch?v=FaLyasJPyUU).

For inspiration, see the drop-down selector in the top left of [docs.python.org](https://docs.python.org/3/)

**Comment by richvdh** [comment] 2022-06-15 15:05
Duplicate of https://github.com/matrix-org/matrix-spec/issues/951

**Closed by richvdh** 2022-06-15 15:05 UTC
Labels: clarification

**Comment by DMRobertson** [comment] 2022-06-15 15:13
Arg thanks. Search-fu failed me.
