### ISSUE TITLE
Ability to redact a room.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-spec#1077] opened 2022-05-22 11:17 UTC
An extension of [mass redactions](https://github.com/matrix-org/matrix-spec-proposals/pull/2244) would be to send a kill flag for a given room by its admins in order to request all servers remove it.

Refiled from https://github.com/vector-im/element-web/issues/2831

**Comment by MadLittleMods** [comment] 2023-04-04 20:58
Seems like a duplicate of https://github.com/matrix-org/matrix-spec/issues/431

**Closed** 2023-04-04 21:23 UTC
Labels: feature
