### ISSUE TITLE
Spec doesn't describe how push rules are to be processed in E2E rooms client side

### ISSUE THREAD

**Issue by clokep** [matrix-org/matrix-spec#1401] opened 2023-01-12 19:56 UTC
**Link to problem area**: https://spec.matrix.org/v1.5/client-server-api/#push-rules

**Issue**
What is wrong? This section, which is under "Client behaviour", seems to describe *Server* behavior (see #600), and fails to describe what clients are supposed to do with this information.

In addition, some of the push rules conditions talk about "unencrypted" events, I don't think this is accurate -- I think the homeserver runs those rules against the encrypted event, and clients are expected to decrypt the event first and then run the push rules. I'm not as confident about this, however.

**Expected behaviour**
How can the issue be fixed? Links to implementations/documents which prove the spec is wrong are appreciated.

The spec should describe how clients are expected to handle push rules.

[matrix-js-sdk's implementation](https://github.com/matrix-org/matrix-js-sdk/blob/7b5e137ec085a78dde17ccc4352b12cf674c1971/src/pushprocessor.ts#L157)

**Comment by anoadragon453** [comment] 2023-01-17 17:00
I asked about this and other general push implementation questions [in the Matrix Client Developers matrix room](https://matrix.to/#/!XXSJTvRPInupfUgQVb:matrix.org/$NOirbbX6kd7z1fJcPZgHzywPR7aJ3hF1iySSzVxYinI?via=pixie.town&via=matrix.org&via=element.io) and had some great feedback. Leaving the conclusions here as a reference until we can clean up the spec.

The point of running push rules client side is:

* for clients that don't process push rules, and
* processing notifications in encrypted rooms.

There is agreement among clients that push rules should stop executing after a match is found (https://github.com/matrix-org/matrix-spec/issues/638) (as otherwise they wouldn't work as intended!).

Nheko ([implementation](https://github.com/Nheko-Reborn/mtxclient/blob/master/lib/structs/pushrules.cpp#L558)):
  - decrypts events before running push rules over them
  - processes push rules in the order given by the account data event

mautrix-go ([implementation](https://github.com/mautrix/go/tree/master/pushrules), powers gomuks, beeper server-side evaluation):
  - decrypts events before running push rules over them
  - processes push rules in the order given by the account data event

Hydrogen doesn't evaluate push rules client-side yet.

The spec doesn't currently clarify whether you should run the rules over your own events (turned this into https://github.com/matrix-org/matrix-spec/issues/1404).

Do clients run push rules over encrypted versions of events too?

clokep: What do clients do in the case of events with both encrypted and unencrypted content?
nico: In the case of Nheko, enencrypted content is merged into the decrypted version of the event (i.e. see `relates_to` field being unencrypted).

**Closed** 2023-03-14 14:57 UTC
Labels: clarification, push, client-server
