### ISSUE TITLE
Time-sensitive room setting

### ISSUE THREAD

**Issue by catfromplan9** [matrix-org/matrix-spec#1453] opened 2023-02-25 03:48 UTC
**Suggestion**
What would you like to see in Matrix? If your idea is vaguely complete enough, we
recommend submitting [an MSC](https://matrix.org/docs/spec/proposals) instead.

After a period configured in the room settings, messages exceeding the defined period should be redacted or made inaccessible. The purpose for this would be to improve privacy

**Comment by turt2live** [comment] 2023-02-25 05:02
Duplicate of https://github.com/matrix-org/matrix-spec/issues/35

**Closed by turt2live** 2023-02-25 05:02 UTC
Labels: improvement
