### ISSUE TITLE
Corporate takeover - Allowing servers to join.

### ISSUE THREAD

**Issue by Biep** [matrix-org/matrix-spec#1662] opened 2023-10-13 19:25 UTC
Servers come and go, and their going can be a painful process for those who have accounts there.
It would be great if a vibrant server could somehow incorporate a soon-to-disappear server.
In the simplest shape, the domain pointing at the moribund server would be changed to point to the vibrant server, and somehow account name clashes would be avoided by looking at the domain, the "server name", the bit after the colon in the account address.
Maybe a smoother approach is possible - e.g. a directory keeping track of which servers were taken over by which servers - so that there is no need to keep all those domains active.  If no Matrix server is found at a given domain, the directory will tell where to login, and some account name change rule will prevent name clashes.
The directory will be connected to the Matrix client the way Identity servers and Integration managers are.

The takeover would ideally be started by the admin of the moribund server, but "takeover in case of death" could be set-up beforehand - letting the vibrant server keep a copy of the data on the moribund server.

Having such a system would make the matrix network way more robust (especially if e.g. matrix.org were willing to accept any defunct servers), as people would have a reasonable certainty that their accounts, wherever they were made, would not suddenly disappear.  Ideally some vibrant server for takeover in case of death would already be set in the default settings for server software.

The protocol should also allow servers simply moving - e.g. halogen.city -> halogen.place - so that no action is needed by the account owner.  Matrix clients could change the server they login to invisibly to the user.

**Comment by turt2live** [comment] 2023-10-13 20:30
This is effectively a duplicate of https://github.com/matrix-org/matrix-spec/issues/246 where a user or server could trigger an account transfer.

**Closed by turt2live** 2023-10-13 20:30 UTC
Labels: improvement
