### ISSUE TITLE
Reactions to Reactions/Second level reactions

### ISSUE THREAD

**Issue by Feliks-WR** [matrix-org/matrix-spec#1961] opened 2024-10-05 13:29 UTC
2nd level  Reactions are when someone reacts to a message, and I react to the reaction e
For example, someone might react 🤣, and I might react ⁉️ to that reaction.

Reason:
Soooo many times, I find myself wanting to react to a reaction.
It would be a REALLY strong magnet towards Matrix, for non Matrix users.

It should be added to the protocol+ Element (X) first, then clients can add their own implementations.

Also, support for these should be added to Synapse as well, so that servers can incorporate the feature easily.

Perhaps, needing to make reactions end to end encrypted may become necessary.

**Comment by richvdh** [comment] 2024-10-06 18:55
Duplicate of https://github.com/matrix-org/matrix-spec/issues/1960. Please stop opening unactionable issues here.

**Closed by richvdh** 2024-10-06 18:55 UTC
Labels: improvement

**Comment by Feliks-WR** [comment] 2024-10-07 13:17
> Duplicate of #1960. Please stop opening unactionable issues here.

Unactionable? Please clarify??
